apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: interactive-shell
  name: interactive-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interactive-shell
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: interactive-shell
      annotations:
        arbfund.com/use-case: "Simple interactive pod to play with"
    spec:
      containers:
        - image: nginx:1.15.8
          imagePullPolicy: IfNotPresent
          name: interactive-shell
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
