apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller-manager
  namespace: consul-ns
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
